    spring:
        datasource:
            username: root
            password: 0594
            url: jdbc:mysql://localhost:3306/sys?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    mybatis:
        mapper-locations: classpath:mapper/*.xml
        configuration:
            log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

    pagehelper:
      helperDialect: mysql
      reasonable: true
      supportMethodsArguments: true
      params: count=countSql




